language: python

python:
  - "3.8"
  - "3.9"

install: pip install tox-travis

script: tox

after_failure:
  - cat .tox/log/*
  - cat .tox/*/log/*

notifications:
  email:
    on_success: never
    on_failure: always
