dynaconf_merge = true
[job]
name = "bray-example"

[job.input]
file_system_id = "fs.in"
path = "@format {this.DEFAULT.input_file}"
fields = ["Integration ID","Site Name","Full Address","Borough","Status"]

[job.output]
file_system_id = "fs.out"
path = "@format {this.DEFAULT.output_file}"

[geoclient]
app_id = "bray-example"
app_key = "s3cret_key"
baseuri = "https://maps.nyc.gov/geoclient/v2"
